[package]
name = "vibe-cast-state"
version = "0.1.0"
edition = "2021"

[dependencies]
vibe-cast-models = { path = "../models" }
tokio = { version = "1", features = ["sync"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
local-ip-address = "0.6"
